### ISSUE TITLE
Где картинка, БЖУ, описание и вес?

### ISSUE THREAD

**Issue by coursar** [AliAlievALive/KFC#2]
https://github.com/AliAlievALive/KFC/blob/33b23554171936020d3e8874b7275c3903f63dd3/src/main/java/Burger.java#L2-L4

**Comment by AliAlievALive** [comment]
Добавил

**Comment by coursar** [comment]
1. Если исправили - закрывайте
2. Issue надо закрывать сообщениями коммита
